defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page_layout"
      css: ""
      sneaky: "false"
  -
    scope:
      path: "sneaky"
      type: "pages"
    values:
      layout: "page_layout"
      css: ""
      sneaky: "true"
  -
    scope:
      path: "_posts/notes"
    values:
      layout: "page_layout"
      css: ""
      category: notes
      sneaky: "true"

markdown: kramdown
mathjax: true
