defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page_layout"
      css: ""
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project_layout" # overrides previous default layout
