defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page_layout"
      css: ""
      sneaky: "false"
  -
    scope:
      path: "sneaky"
      type: "pages"
    values:
      layout: "page_layout"
      css: ""
      sneaky: "true"

markdown: kramdown
kramdown:
  math_engine: mathjax
